Improve badge server test functionality.

diff --git a/docs/ci/badge-server-test b/docs/ci/badge-server-test
--- a/docs/ci/badge-server-test
+++ b/docs/ci/badge-server-test
@@ -1,4 +1,4 @@
-#!/bin/bash -ex
+#!/bin/bash -e
 # Startup badge service and test it
 ./popper badge service &
 
@@ -8,59 +8,92 @@ sleep 2
 if [ 'pgrep popper' >/dev/null ]
 then
     echo "Badge service running. Starting curl tests:"
-    curl -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha1/invalid
-    sleep 2
+    curl -s -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha1/invalid
+    echo "Assert invalid: "
+    if ! curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/status | grep invalid; then
+        exit 1
+    fi
+    sleep 1
 
-    curl -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha2/failed
-    sleep 2
+    curl -s -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha2/failed
+    echo "Assert failed: "
+    if ! curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/status | grep failed; then
+        exit 1
+    fi
+    sleep 1
 
-    curl -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha3/ok
-    sleep 2
+    curl -s -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha3/ok
+    echo "Assert ok: "
+    if ! curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/status | grep ok; then
+        exit 1
+    fi
+    sleep 1
+    
+    curl -s -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha4/gold
+    echo "Assert gold: "
+    if ! curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/status | grep gold; then
+        exit 1
+    fi
+    sleep 1
 
-    curl -d --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha4/gold
-    sleep 2
+    echo "Testing status.svg: "
+    curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/status.svg   
+    sleep 1
 
-    curl --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/status.svg
-    sleep 2
+    echo "Testing history: "
+    curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/history
+    sleep 1
 
-    curl --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/status
-    sleep 2
+    echo "Testing status.svg: "
+    curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha1/status.svg
+    sleep 1
 
-    curl --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/history
-    sleep 2
+    curl -s -d --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/testSha1/gold
+    echo "Assert gold: "
+    if ! curl -s --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/status | grep gold; then
+        exit 1
+    fi
+    sleep 1
 
-    curl --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/testSha1/status.svg
-    sleep 2
+    curl -s -d --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/testSha2/failed
+    echo "Assert failed: "
+    if ! curl -s --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/status | grep failed; then
+        exit 1
+    fi
+    sleep 1
 
-    curl -d --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/testSha1/gold
-    sleep 2
+    echo "Testing history: "
+    curl -s --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/history
+    sleep 1
 
-    curl -d --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/testSha2/failed
-    sleep 2
-
-    curl --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/history
-    sleep 2
-
-    echo "Curl tests complete. Shutting down badge service."
-
+    echo "Shutting down badge service to test status.db"
     kill "$myId"
 
     if [ -e status.db ]
     then
         echo "status.db found, continuing test."
     else
-        echo "PROBLEM: status.db not found."
+        echo "status.db not found."
+        exit 1
     fi
 
     ./popper badge service &
     myId=$!
-    sleep 2
+    sleep 1
 
-    curl --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/history
-    sleep 2
+    echo "Testing history: "
+    curl -s --url http://127.0.0.1:9090/testOrg1/testRepo1/testExp1/history
+    sleep 1
 
-    curl --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/history
-    sleep 2
+    echo "Testing history: "
+    curl -s --url http://127.0.0.1:9090/testOrg1/testRepo2/testExp1/history
+    sleep 1
+
+    echo "Testing non-existent repo:"
+     if ! curl -s --url http://127.0.0.1:9090/testOrg2/testRepo3/testExp4/status | grep invalid; then
+        exit 1
+    fi
+    sleep 1
 
     echo "Tests complete, shutting down."
     kill "$myId"
